### ISSUE TITLE
Full page view error

### ISSUE THREAD

**Issue by Aspireve** [Dhruvrg/portfolio#1]
I guess this page doesnt extend to the entire screen, I guess this could be fixed with putting the min-height to 100vh
Else I guess the entire site looks awesome!! Kudos!!

| ![Screenshot from 2024-06-20 18-19-17](https://github.com/Dhruvrg/portfolio/assets/93852415/72367096-d732-4dfd-8211-a65f46925bfb) |
| -- |
|Screenshot of the [page](https://portfolio-internhip.vercel.app/projects) |

**Comment by Dhruvrg** [comment]
> I guess this page doesnt extend to the entire screen, I guess this could be fixed with putting the min-height to 100vh
> Else I guess the entire site looks awesome!! Kudos!!
> 
> 
> | ![Screenshot from 2024-06-20 18-19-17](https://github.com/Dhruvrg/portfolio/assets/93852415/72367096-d732-4dfd-8211-a65f46925bfb) |
> | -- |
> |Screenshot of the [page](https://portfolio-internhip.vercel.app/projects) |
> 

Thank you Steve for identifying and reporting the bug in the code. I will fix it

**Comment by Aspireve** [comment]
So should I close this issue?
